{{- if and (hasKey .Values "rabbitmqManagementEnabled") (hasKey .Values "rabbitmqManagementIngressEnabled") }}
{{- if and (.Values.rabbitmqManagementEnabled) (.Values.rabbitmqManagementIngressEnabled) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq-management-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: rabbitmq
          servicePort: 15672
{{- end -}}
{{- end -}}

