{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: standardgateway-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  {{ if .Values.ingress.certificateSecretName -}}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.certificateSecretName }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /swagger
        backend:
          serviceName: standardgateway
          servicePort: 8443
      - path: /secretssafe/api
        backend:
          serviceName: standardgateway
          servicePort: 8443
    {{ if ne .Values.ingress.host "any" -}}
    host: {{ .Values.ingress.host }}
    {{- end -}}
{{- end -}}
