kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer 
spec:
  type: ClusterIP
  clusterIP: "None"
  ports:
{{- if hasKey .Values "rabbitmqManagementEnabled" }} 
{{- if .Values.rabbitmqManagementEnabled }} 
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
{{- end }}
{{- end }}
   - name: amqp
     protocol: TCP
     port: 5671
     targetPort: 5671
  selector:
    app: rabbitmq
